import localFont from "next/font/local";
import {Roboto} from 'next/font/google'

import "./globals.css";
import Header from "./_component/Header";
import Footer from "./_component/Footer";

const geistSans = Roboto({
  subsets: ["latin"],
  variable: "--font-Roboto",
  weight: "700",
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} antialiased`}
      >
        <Header/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
